<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Tallya Lutfak" />
    
    <link rel="shortcut icon" type="image/x-icon" href="/img/favicon.ico">
    <title>Predicting Effectivenss of Cognitive Therapy Program on Depressed Patients</title>
    <meta name="generator" content="Hugo 0.61.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">

      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="/blog/">BLOG</a></li>
        
        <li><a href="/projects/">PROJECTS</a></li>
        
        <li><a href="/resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      
      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="/project2/">Predicting Effectivenss of Cognitive Therapy Program on Depressed Patients</a></strong>
          </h3>
        </div>
        <div class="blog-title">
          <h4>
          January 1, 0001
            &nbsp;&nbsp;
            
          </h4>
        </div>
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<p><em>The dataset I used for my project was the Beat the Blues (BtheB) dataset. It is a longitudinal study from a clinical trial that contains data on the effects of a multimedia program “Beat the Blues”, that serves as cognitive therapy, on depression levels of depressed patients. The dataset has 100 observations and 8 variables. The first variable is a catergorical variable that specfies whether or not the patient took anti-depressent drugs. The next variable is length which indicates whether the current episode of depression has lasted more than or less than six months. Treatment group is the last catergorical variable and states whether the patient recieved the Beat the Blues treatment or thier usual treatment. The rest of the variables which includes bdi.pre, bdi.2m, bdi.4m, bdi.6m, bdi.8m are all numeric. They indicate the Beck Depression Inventory II score before, 2 months, 4 months, 6 months, and 8 months after the treatment respectively. </em></p>
<pre class="r"><code>options(repos=&quot;https://cran.rstudio.com&quot; )



library(HSAUR)

dataset1 &lt;-(BtheB)</code></pre>
<p><em>Perform a MANOVA testing whether any of your numeric variables (or a subset of them, if including them all doesn’t make sense) show a mean difference across levels of one of your categorical variables (3). If they do, perform univariate ANOVAs to find response(s) showing a mean difference across groups (3), and perform post-hoc t tests to find which groups differ (3). Discuss the number of tests you have performed, calculate the probability of at least one type I error (if unadjusted), and adjust the significance level accordingly (bonferroni correction) before discussing significant differences (3). Briefly discuss assumptions and whether or not they are likely to have been met (2).</em></p>
<pre class="r"><code>question1 &lt;-manova(cbind(bdi.2m,bdi.4m,bdi.6m)~treatment, data=dataset1)
summary(question1)</code></pre>
<pre><code>## Df Pillai approx F num Df den Df Pr(&gt;F)
## treatment 1 0.19598 4.3874 3 54 0.007788 **
## Residuals 56
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>summary.aov(question1)</code></pre>
<pre><code>## Response bdi.2m :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## treatment 1 1174.5 1174.50 12.998 0.0006642 ***
## Residuals 56 5060.1 90.36
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response bdi.4m :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## treatment 1 952.2 952.16 8.6134 0.004831 **
## Residuals 56 6190.4 110.54
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response bdi.6m :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## treatment 1 717.5 717.52 6.3048 0.01495 *
## Residuals 56 6373.1 113.81
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## 42 observations deleted due to missingness</code></pre>
<pre class="r"><code>dataset1%&gt;%na.omit()%&gt;%group_by(treatment)%&gt;%summarize(mean(bdi.2m), mean(bdi.4m), mean(bdi.6m))</code></pre>
<pre><code>## # A tibble: 2 x 4
##   treatment `mean(bdi.2m)` `mean(bdi.4m)` `mean(bdi.6m)`
##   &lt;fct&gt;              &lt;dbl&gt;          &lt;dbl&gt;          &lt;dbl&gt;
## 1 TAU                 20.1           17.8          15.9 
## 2 BtheB               10.9           10.3           9.48</code></pre>
<pre class="r"><code>pairwise.t.test(dataset1$bdi.2m, dataset1$treatment, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  dataset1$bdi.2m and dataset1$treatment 
## 
##       TAU 
## BtheB 0.03
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(dataset1$bdi.4m, dataset1$treatment, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  dataset1$bdi.4m and dataset1$treatment 
## 
##       TAU  
## BtheB 0.041
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(dataset1$bdi.6m, dataset1$treatment, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  dataset1$bdi.6m and dataset1$treatment 
## 
##       TAU  
## BtheB 0.015
## 
## P value adjustment method: none</code></pre>
<p><em>A (MANOVA) was conducted to determine the effect of the treatment(BtheB, TAU (treatment as usual)) on three dependent variables (bdi.2m, bdi.4m, bdi.6m) and significant differences were found among the 2 treatments on the three dependent measures (Pillai trace = 0.19598, F = 4.3874, p &lt; 0.05. Univariate analyses of variance (ANOVAs) for each dependent variable were conducted as follow-up tests to the MANOVA,the univariate ANOVAs for bdi.2m, bdi.4m, bdi.6m, were also all significant with p&lt;0.05. Lastly, post-hoc analysis was performed conducting pairwise comparisons to determine which Treatment differed in Beck Depression Inventory II after 2,4,and 6 months. Overall, 10 hypothesis tests have been performed and the probability that I have made at least one type I error 0.5; The boneferroni adjusted significance level I should use is 0.005. It was found that both treatments did not differ signifncantly from each other in terms of Beck Depression Inventory II score after 2 months, 4 months and 6 months of each treatment being administered after adjusting for multiple comparisons (bonferroni). When considering the many assumptions for MANOVA such as multivareat normality of DVs, Homogeneity of within-group covarience matrices, linear relationships among DVs, no multicollinearity were likely not met. </em></p>
<p><em>(10 pts) Perform some kind of randomization test on your data (that makes sense). This can be anything you want! State null and alternative hypotheses, perform the test, and interpret the results (7). Create a plot visualizing the null distribution and the test statistic (3).</em></p>
<pre class="r"><code>dataset1%&gt;%group_by(drug)%&gt;%
  summarize(means=mean(bdi.pre))%&gt;%summarize(`mean_diff:`=diff(means))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   `mean_diff:`
##          &lt;dbl&gt;
## 1         4.04</code></pre>
<pre class="r"><code>set.seed(348)
rand_dist&lt;-vector()

for(i in 1:5000){
new&lt;-data.frame(bdi.pre=sample(dataset1$bdi.pre), druguse=dataset1$drug) 
rand_dist[i]&lt;-mean(new[new$drug==&quot;No&quot;,]$bdi.pre)-
 mean(new[new$drug==&quot;Yes&quot;,]$bdi.pre)
}

{hist(rand_dist,main=&quot;&quot;,ylab=&quot;&quot;); abline(v = 4.037338,col=&quot;red&quot;)}</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-3-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>mean(rand_dist&gt;4.037338)*2</code></pre>
<pre><code>## [1] 0.074</code></pre>
<pre class="r"><code>t.test(data=dataset1, bdi.pre~drug)</code></pre>
<pre><code>##
## Welch Two Sample t-test
##
## data: bdi.pre by drug
## t = -1.7995, df = 74.911, p-value = 0.07597
## alternative hypothesis: true difference in means is not
equal to 0
## 95 percent confidence interval:
## -8.5069019 0.4322266
## sample estimates:
## mean in group No mean in group Yes
## 21.55357 25.59091</code></pre>
<p><em>The Null Hypothesis is that the mean starting Beck Depression Inventory II score is the same for patients on vs patients off anti-depressents. The Alternative Hypothesis is that the mean starting Beck Depression Inventory II score is different for patients on verus off anti depressents. After generating a distribution of 5000 mean differnces via a randomization test, the p value was 0.0644 which is larger than 0.05. Thus, we can refuse to reject the null hypothesis and say that there is not a signifcant difference in the pre-treatment Beck Depression Inventory score for patients on versus off anti-depressents; the independet t test for compariosn confimred this interpretation.</em></p>
<p><em>Build a linear regression model predicting one of your response variables from at least 2 other variables, including their interaction. Mean-center any numeric variables involved in the inter- action.</em></p>
<pre class="r"><code>library(lmtest)
library(sandwich)
library(tidyverse)
library(dplyr)

dataset1$bdi.8m_c1 &lt;-dataset1$bdi.8m-mean(dataset1$bdi.8m,na.rm=TRUE)

dataset1$bdi.pre_c1 &lt;-dataset1$bdi.pre-mean(dataset1$bdi.pre,na.rm=TRUE)

fit &lt;-lm(bdi.8m_c1 ~ treatment * bdi.pre_c1, data=dataset1)
summary(fit)</code></pre>
<pre><code>##
## Call:
## lm(formula = bdi.8m_c1 ~ treatment * bdi.pre_c1, data =
dataset1)
##
## Residuals:
## Min 1Q Median 3Q Max
## -18.8875 -5.3813 0.0658 3.7307 19.5346
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 2.0088 1.7005 1.181 0.2433
## treatmentBtheB -3.9839 2.3630 -1.686 0.0983 .
## bdi.pre_c1 0.5779 0.2139 2.702 0.0095 **
## treatmentBtheB:bdi.pre_c1 -0.3465 0.2626 -1.320 0.1932
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 8.46 on 48 degrees of freedom
## (48 observations deleted due to missingness)
## Multiple R-squared: 0.222, Adjusted R-squared: 0.1734
## F-statistic: 4.566 on 3 and 48 DF, p-value: 0.006818</code></pre>
<pre class="r"><code>dataset1%&gt;%ggplot(aes(x=bdi.8m_c1, y=treatment, color=bdi.pre)) + geom_point()+geom_line()</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-4-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>bptest(fit)#0.008</code></pre>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  fit
## BP = 11.831, df = 3, p-value = 0.007985</code></pre>
<pre class="r"><code>resids&lt;-fit$residuals
fitvals&lt;-fit$fitted.values
ggplot()+geom_point(aes(fitvals,resids))+geom_hline(yintercept=0, color=&#39;red&#39;)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-4-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>shapiro.test(resids)#0.8238</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  resids
## W = 0.98666, p-value = 0.8238</code></pre>
<pre class="r"><code>coeftest(fit,vcov=vcovHC(fit))</code></pre>
<pre><code>##
## t test of coefficients:
##
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 2.00885 2.20444 0.9113 0.3667
## treatmentBtheB -3.98389 2.49231 -1.5985 0.1165
## bdi.pre_c1 0.57790 0.33835 1.7080 0.0941 .
## treatmentBtheB:bdi.pre_c1 -0.34653 0.35556 -0.9746
0.3346
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>summary(fit)$r.sq</code></pre>
<pre><code>## [1] 0.2220036</code></pre>
<p><em>Based on regression results, when no treatment is applied and the “bdi.pre” (starting Beck Depression Inventory II Score) is zero, the Beck Depression Inventory II Score after 8 months of treatment is 2.0088. On average, for every 1 unit increase in the Beat the Blues treatment, the Beck Depression Inventory II Score after 8 months of treatment decreases by about 3.9839 units. For every one unit increase in ‘bdi.pre’, on average, the Beck Depression Inventory II Score after 8 months of treatment increases by about 0.5779 units. On average, for every one unit increase in the interaction between treatment and pre-treatment Beck Depression Inventory II Score, the Beck Depression Inventory II Score after 8 months of Beat the Blues treatment decreases by -0.3465. When looking at the assumptions, it failed to meet the homsckedasticty assumption as the Breusch-Pagan test returned a p-value less than 0.05 so the null hypothesis of homescadaskcity was accepted. Contrastly, it met the normality assumption as after performing the Shapiro-Wilk test p-value was greater than 0.05 so I failed to reject the null hypothesis of normality. Lastly, through looking at the coded graph it met the linearity assumption as all the lines were straight. When comparing robust SE and original SE, the robust SE increased for all the coeffients. The treatment Beat the Blues, the interaction between Beat the Blues and pre-treatment bdi score, and the pre-treatment bdi score had no signigcnat effect on the patients Beck Depression Inventory Score 8 months after treatment as the p-value were less than 0.05 (0.1165 and 0.3346 respectively). However, before computing the roboust SE, the p-value of bdi.pre was 0.0095 (less than 0.05) and thus had a signifcant effect on Beck Depression INventory Score after 8 months. Overall, my model explains 22.20% of the variation in the outcome. </em>
*</p>
<p><em>(5 pts) Rerun same regression model (with interaction), but this time compute bootstrapped standard errors. Discuss any changes you observe in SEs and p-values using these SEs compared to the original SEs and the robust SEs)</em></p>
<pre class="r"><code>samp_distn&lt;-replicate(5000, {
  boot_data&lt;-dataset1[sample(nrow(dataset1),replace=TRUE),]
  fit1&lt;-lm(bdi.8m_c1~treatment*bdi.pre_c1,data=boot_data)
  coef(fit1)
})
## Estimated SEs
samp_distn%&gt;%t%&gt;%as.data.frame%&gt;%summarize_all(sd)</code></pre>
<pre><code>## (Intercept) treatmentBtheB bdi.pre_c1
treatmentBtheB:bdi.pre_c1
## 1 2.066198 2.364539 0.317116 0.3371881</code></pre>
<p><em>The Bootstrapped SE are less than the roboust SE for all variables and greater than all the original SE as well except for Treatment which is slightly lower.</em></p>
<ul>
<li>Perform a logistic regression predicting a binary categorical variable (if you don’t have
one, make/get one) from at least two explanatory variables (interaction not necessary)*</li>
</ul>
<pre class="r"><code>dataset1$y&lt;-ifelse(dataset1$drug==&#39;Yes&#39;,1,0)
fit3&lt;-glm(drug~treatment+length,data=dataset1,family=binomial(link=&quot;logit&quot;))
coeftest(fit3)</code></pre>
<pre><code>##
## z test of coefficients:
##
## Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) -0.59956 0.37542 -1.5970 0.110258
## treatmentBtheB 1.20978 0.42874 2.8217 0.004776 **
## length&gt;6m -0.58680 0.42560 -1.3788 0.167964
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>exp(coef(fit3))</code></pre>
<pre><code>##    (Intercept) treatmentBtheB      length&gt;6m 
##      0.5490540      3.3527448      0.5561039</code></pre>
<pre class="r"><code>dataset1$probability &lt;-predict(fit3, data=dataset1, type = &quot;response&quot;)
table(predict=as.numeric(dataset1$probability&gt;.5),truth=dataset1$y)%&gt;%addmargins</code></pre>
<pre><code>##        truth
## predict   0   1 Sum
##     0    34  14  48
##     1    22  30  52
##     Sum  56  44 100</code></pre>
<pre class="r"><code>Accurancy &lt;-(34+30)/100
TPR &lt;- 30/44
TNR&lt;- 34/56
PVR&lt;-30/52

mean(dataset1[dataset1$y==1,]$probability&gt;.5)</code></pre>
<pre><code>## [1] 0.6818182</code></pre>
<pre class="r"><code>ggplot(dataset1)+aes(probability, drug)+geom_line()</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-6-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>library(plotROC)
ROCplot&lt;-ggplot(dataset1)+geom_roc(aes(d=y,m=probability), n.cuts=0)+
geom_segment(aes(x=0,xend=1,y=0,yend=1),lty=2)
ROCplot</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-6-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>calc_auc(ROCplot)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.6781656</code></pre>
<pre class="r"><code>class_diag&lt;-function(probs,truth){
 tab&lt;-table(factor(probs&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),truth)
 acc=sum(diag(tab))/sum(tab)
 sens=tab[2,2]/colSums(tab)[2]
 spec=tab[1,1]/colSums(tab)[1]
 ppv=tab[2,2]/rowSums(tab)[2]
 if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE) truth&lt;-as.numeric(truth)-1
 #CALCULATE EXACT AUC
 ord&lt;-order(probs, decreasing=TRUE)
 probs &lt;- probs[ord]; truth &lt;- truth[ord]
 TPR=cumsum(truth)/max(1,sum(truth))
 FPR=cumsum(!truth)/max(1,sum(!truth))
 dup&lt;-c(probs[-1]&gt;=probs[-length(probs)], FALSE)
 TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
 n &lt;- length(TPR)
 auc&lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )
 data.frame(acc,sens,spec,ppv,auc)
} 

set.seed(1234)
k=10 
data1&lt;-dataset1[sample(nrow(dataset1)),] 
folds&lt;-cut(seq(1:nrow(dataset1)),breaks=k,labels=F) 
diags&lt;-NULL
for(i in 1:k){
 
 train&lt;-data1[folds!=i,]
 test&lt;-data1[folds==i,]
 truth&lt;-test$y
 
 fit5&lt;-glm(y~treatment+bdi.pre_c1,data=train,family=&quot;binomial&quot;)
 probs&lt;-predict(fit5,newdata = test,type=&quot;response&quot;)
 
 diags&lt;-rbind(diags,class_diag(probs,truth))
}

apply(diags,2,mean)</code></pre>
<pre><code>##       acc      sens      spec       ppv       auc 
## 0.6400000 0.5666667 0.7386905 0.6516667 0.7163690</code></pre>
<p><em>When no treatment is applied and the length of the depressive episode is 0 months, the odds of the patients having used anti-depressents is 0.5491. When the length of the depressive episode is held constant, for every one unit increase in the Beat the Blues treatment, the odds of the pateint having taken anti-depressents increases by 3.353. When the application of treatment is held constant, for every 1 month increases in the length of the depressive episode, the odds of the patient having used anti-depressents increases by 0.5561. The Accuracy (the proportion of correctly classified cases) was 0.64, the Sensitivity (True Positive Rate, TPR) which is proportion of patients using drugs (1 cases) coreectly classified was 0.681, Specficity which is the proportion of pateints not using drugs (“0 cases”) correctly classified was 0.607.Precsion (Positive Predictive Value, PPV) proportion classified as using drugs who actaully use drugs was 0.5769. The AUC was 0.6781which is the probability that a randomly selected person taking drugs has a higher prediction than a randomly selected person not taking drugs. Overall, with it being 0.681 length of depressive episode and pre-treatment BDI are moderate preictors of a pateints taking anti-depressents. After the 10 Fold CV, the accurancy was 0.60, the senstivity was 0.4433, the specficity was 0.6957, the ppv was 0.60, and the auc was 0.6747.</em></p>
<ol start="6" style="list-style-type: decimal">
<li></li>
</ol>
<pre class="r"><code>library(glmnet)



fit50&lt;-glm(bdi.8m~ -1 + as.factor(length)+as.factor(treatment)+as.factor(drug)+bdi.pre, data = dataset1)
model.matrix(fit)</code></pre>
<pre><code>## (Intercept) treatmentBtheB bdi.pre_c1
treatmentBtheB:bdi.pre_c1
## 2 1 1 8.67 8.67
## 4 1 1 -2.33 -2.33
## 6 1 1 -16.33 -16.33
## 7 1 0 -6.33 0.00
## 8 1 0 -3.33 0.00
## 9 1 1 -5.33 -5.33
## 10 1 1 -3.33 -3.33
## 11 1 0 6.67 0.00
## 14 1 0 6.67 0.00
## 15 1 1 -0.33 -0.33
## 16 1 0 -7.33 0.00
## 18 1 1 -10.33 -10.33
## 19 1 0 13.67 0.00
## 20 1 1 11.67 11.67
## 22 1 0 2.67 0.00
## 29 1 1 12.67 12.67
## 30 1 1 -13.33 -13.33
## 31 1 0 3.67 0.00
## 32 1 1 -5.33 -5.33
## 33 1 1 -12.33 -12.33
## 35 1 1 20.67 20.67
## 37 1 0 -2.33 0.00
## 38 1 0 10.67 0.00
## 40 1 0 14.67 0.00
## 42 1 0 -3.33 0.00
## 43 1 0 -6.33 0.00
## 45 1 1 18.67 18.67
## 47 1 1 9.67 9.67
## 50 1 0 12.67 0.00
## 53 1 0 7.67 0.00
## 56 1 1 -16.33 -16.33
## 61 1 0 -1.33 0.00
## 62 1 0 -0.33 0.00
## 67 1 0 -6.33 0.00
## 71 1 1 -14.33 -14.33
## 75 1 0 -9.33 0.00
## 76 1 1 4.67 4.67
## 77 1 1 -8.33 -8.33
## 78 1 1 -1.33 -1.33
## 80 1 0 -2.33 0.00
## 81 1 0 3.67 0.00
## 83 1 0 -13.33 0.00
## 84 1 0 -2.33 0.00
## 86 1 1 12.67 12.67
## 88 1 0 11.67 0.00
## 89 1 1 9.67 9.67
## 90 1 1 -4.33 -4.33
## 94 1 1 -4.33 -4.33
## 95 1 1 -7.33 -7.33
## 96 1 1 -7.33 -7.33
## 98 1 1 -12.33 -12.33
## 99 1 0 -10.33 0.00
## attr(,&quot;assign&quot;)
## [1] 0 1 2 3
## attr(,&quot;contrasts&quot;)
## attr(,&quot;contrasts&quot;)$treatment
## [1] &quot;contr.treatment&quot;</code></pre>
<pre class="r"><code>set.seed(1234)
x&lt;-model.matrix(fit50)
x&lt;-scale(x)
y&lt;-as.matrix(na.omit(dataset1$bdi.8m))

cv2&lt;-cv.glmnet(x,y)
lasso2&lt;-glmnet(x,y,lambda=cv2$lambda.1se)
coef(cv2)</code></pre>
<pre><code>## 6 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                                       1
## (Intercept)                1.113462e+01
## as.factor(length)&lt;6m      -9.653107e-01
## as.factor(length)&gt;6m       5.165502e-16
## as.factor(treatment)BtheB  .           
## as.factor(drug)Yes         .           
## bdi.pre                    9.300352e-02</code></pre>
<pre class="r"><code>set.seed(1234)
k=10 
data2&lt;-dataset1[sample(nrow(dataset1)),]

folds2&lt;-cut(seq(1:nrow(dataset1)),breaks=k,labels=F)
diags1&lt;-NULL
for(i in 1:k){
 
 train1&lt;-data2[ folds!=i,]
 test1&lt;-data2[ folds==i,]
 truth2&lt;-test1$bdi.8m
 
 fit60&lt;-glm(bdi.8m~as.factor(length)+bdi.pre, data = train1)
 probs3&lt;-predict(fit60,newdata = test1,type=&quot;response&quot;)

diags&lt;-mean((truth2-probs3)^2)
}
mean(diags1)</code></pre>
<pre><code>## [1] NA</code></pre>
<pre class="r"><code>summary(fit50)</code></pre>
<pre><code>##
## Call:
## glm(formula = bdi.8m ~ -1 + as.factor(length) +
as.factor(treatment) +
## as.factor(drug) + bdi.pre, data = dataset1)
##
## Deviance Residuals:
## Min 1Q Median 3Q Max
## -16.1579 -3.6418 -0.2671 2.9920 20.3866
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## as.factor(length)&lt;6m 4.0619 3.3204 1.223 0.2273
## as.factor(length)&gt;6m 10.0763 3.8976 2.585 0.0129 *
## as.factor(treatment)BtheB -3.0815 2.3837 -1.293 0.2024
## as.factor(drug)Yes -2.1906 2.4776 -0.884 0.3811
## bdi.pre 0.2649 0.1355 1.955 0.0565 .
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## (Dispersion parameter for gaussian family taken to be
65.64442)
##
## Null deviance: 10863.0 on 52 degrees of freedom
## Residual deviance: 3085.3 on 47 degrees of freedom
## (48 observations deleted due to missingness)
## AIC: 371.89
##
## Number of Fisher Scoring iterations: 2</code></pre>
<pre class="r"><code>summary(fit60)</code></pre>
<pre><code>##
## Call:
## glm(formula = bdi.8m ~ as.factor(length) + bdi.pre, data
= train1)
##
## Deviance Residuals:
## Min 1Q Median 3Q Max
## -15.1827 -4.0920 -0.5375 4.6034 23.5873
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 1.9682 2.9148 0.675 0.5030
## as.factor(length)&gt;6m 6.1639 2.4045 2.563 0.0138 *
## bdi.pre 0.2300 0.1235 1.863 0.0690 .
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## (Dispersion parameter for gaussian family taken to be
59.30091)
##
## Null deviance: 3570.0 on 47 degrees of freedom
## Residual deviance: 2668.5 on 45 degrees of freedom
## (42 observations deleted due to missingness)
## AIC: 337.09
##
## Number of Fisher Scoring iterations: 2</code></pre>
<p><em>The only variables retained were length and pre.bdi. Comparatively, the out of sample RMSE was higher than the original.</em></p>

              <hr>
              <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div>
            </div>
          </div>
          <hr>
        <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div>
        </div>
      </div>
      
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="/js/docs.min.js"></script>
<script src="/js/main.js"></script>

<script src="/js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
